import boto3, json, os
from datetime import datetime
from collections import defaultdict

dynamodb = boto3.resource('dynamodb')
sns      = boto3.client('sns')

DYNAMO_TABLE = os.environ['DYNAMO_TABLE']
SNS_ARN      = os.environ['SNS_ARN']

def lambda_handler(event, context):
    table    = dynamodb.Table(DYNAMO_TABLE)
    response = table.scan()
    items    = response.get('Items', [])

    print(f"📊 Found {len(items)} records in DynamoDB")

    if not items:
        print("❌ No records found — skipping report")
        return {'statusCode': 200, 'body': 'No data'}

    # Aggregate the data
    total_revenue  = 0
    region_revenue = defaultdict(float)
    product_units  = defaultdict(int)
    product_revenue = defaultdict(float)

    for item in items:
        amount   = float(item.get('total_amount', 0))
        quantity = int(item.get('quantity', 0))
        region   = item.get('region',  'Unknown')
        product  = item.get('product', 'Unknown')

        total_revenue          += amount
        region_revenue[region] += amount
        product_units[product] += quantity
        product_revenue[product] += amount

    # Find top performers
    top_region  = max(region_revenue,  key=region_revenue.get)
    top_product = max(product_revenue, key=product_revenue.get)

    # Build region breakdown
    region_lines = '\n'.join(
        f"   {r:<10} : ${round(v, 2)}"
        for r, v in sorted(region_revenue.items(), key=lambda x: -x[1])
    )

    # Build product breakdown
    product_lines = '\n'.join(
        f"   {p:<15} : ${round(product_revenue[p], 2)} ({product_units[p]} units)"
        for p in sorted(product_revenue, key=lambda x: -product_revenue[x])
    )

    # Format the email report
    report = f"""
╔══════════════════════════════════════════════╗
   📊 DAILY SALES REPORT
   {datetime.utcnow().strftime('%A, %B %d %Y — %H:%M UTC')}
╚══════════════════════════════════════════════╝

SUMMARY
───────────────────────────────────────────────
  Total Records   : {len(items)}
  Total Revenue   : ${round(total_revenue, 2)}
  Top Region      : {top_region} (${round(region_revenue[top_region], 2)})
  Top Product     : {top_product} (${round(product_revenue[top_product], 2)})

REVENUE BY REGION
───────────────────────────────────────────────
{region_lines}

REVENUE BY PRODUCT
───────────────────────────────────────────────
{product_lines}

───────────────────────────────────────────────
  Generated by AWS Lambda + DynamoDB
  Account: ap-south-1
╚══════════════════════════════════════════════╝
    """

    # Send email via SNS
    sns.publish(
        TopicArn=SNS_ARN,
        Subject=f"📊 Daily Sales Report — {datetime.utcnow().strftime('%Y-%m-%d')}",
        Message=report
    )

    print(report)
    print(f"✅ Report sent via SNS to all subscribers!")

    return {
        'statusCode': 200,
        'body': json.dumps({
            'records':       len(items),
            'total_revenue': round(total_revenue, 2),
            'top_region':    top_region,
            'top_product':   top_product
        })
    }
